init:
    pip install -r requirements.txt

test:
    nosetests

installer:
	pip install py2app
	pip install ez_setup
	python setup.py py2app
	#pyinstaller --onefile goproorg/ui.py -p goproorg/ -n gopro-organizer